#### Advantages of Numpy

- Memory efficient
- Speed
- Ease of use
- Lot of functionalities to do mathematical operations easily.

## how to import numpy package

In [135]:
import numpy as np

In [136]:
# multiply all element in the list
arr1 = np.array([34, 21, 89, 45, 67, 90, 88])
print(arr1 * 2)

[ 68  42 178  90 134 180 176]


In [137]:
# Convert Into Str
list2 = [34, 78, 90, 55, 44, 32, 76.5, 'Python']
np.array(list2)

array(['34', '78', '90', '55', '44', '32', '76.5', 'Python'], dtype='<U32')

### Using functions to create Arrays

- np.arange
- np.ones
- np.zeros
- np.full
- np.linspace
- np.random.random
- np.random.randint
- np.diag
- np.eye

#### np.arange function

In [138]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
np.arange(5, 26)  #(start, stop+1)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25])

In [140]:
np.arange(10, 91, 10)  #(start, stop+1, step)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

#### 2d array

In [141]:
np.arange(24).reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

#### np.ones function

In [142]:
np.ones(25)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [143]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [144]:
np.ones((5,4)) * 21

array([[21., 21., 21., 21.],
       [21., 21., 21., 21.],
       [21., 21., 21., 21.],
       [21., 21., 21., 21.],
       [21., 21., 21., 21.]])

#### np.zeros function

In [145]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [146]:
np.zeros((6,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### np.full function

In [147]:
np.full((5,5), 10000)

array([[10000, 10000, 10000, 10000, 10000],
       [10000, 10000, 10000, 10000, 10000],
       [10000, 10000, 10000, 10000, 10000],
       [10000, 10000, 10000, 10000, 10000],
       [10000, 10000, 10000, 10000, 10000]])

#### np.eye function

In [148]:
np.eye(5)   #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [149]:
np.eye(5) * 10

array([[10.,  0.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.,  0.],
       [ 0.,  0., 10.,  0.,  0.],
       [ 0.,  0.,  0., 10.,  0.],
       [ 0.,  0.,  0.,  0., 10.]])

#### np.diag function

In [150]:
np.diag([10,11,12,13,14,15])

array([[10,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0, 12,  0,  0,  0],
       [ 0,  0,  0, 13,  0,  0],
       [ 0,  0,  0,  0, 14,  0],
       [ 0,  0,  0,  0,  0, 15]])

#### np.random.random function

In [151]:
np.random.random(5)   #array of random numbers between 0 and 1

array([0.69820051, 0.92495505, 0.29626512, 0.13190277, 0.53517626])

#### np.random.randint function

In [152]:
np.random.randint(50)   #a random number between 0 and 49

47

In [153]:
np.random.randint(1, 7)

6

In [155]:
np.random.randint(10, 51, size = 10)

array([26, 24, 40, 25, 28, 41, 41, 35, 22, 30])

In [156]:
np.random.randint(10,51, size = (1000000, 100))

array([[13, 42, 25, ..., 43, 45, 14],
       [40, 29, 44, ..., 46, 35, 40],
       [23, 24, 40, ..., 37, 18, 33],
       ...,
       [38, 43, 46, ..., 32, 35, 29],
       [34, 12, 22, ..., 42, 40, 49],
       [23, 32, 22, ..., 22, 37, 47]])

#### np.linspace(linearly spaced values) function

In [157]:
np.linspace(0,50,9)   #(start, stop, no of data points)

array([ 0.  ,  6.25, 12.5 , 18.75, 25.  , 31.25, 37.5 , 43.75, 50.  ])

In [158]:
np.linspace(0, 100, 200000)

array([0.000000e+00, 5.000025e-04, 1.000005e-03, ..., 9.999900e+01,
       9.999950e+01, 1.000000e+02])

### Indexing and Slicing

In [159]:
arr = np.arange(10, 91, 10).reshape(3,3)

In [160]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [161]:
arr[1,0]

40

In [162]:
arr[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [163]:
(arr >= 50) & (arr <= 80)

array([[False, False, False],
       [False,  True,  True],
       [ True,  True, False]])

In [164]:
arr[(arr >= 50) & (arr <= 80)]

array([50, 60, 70, 80])

In [165]:
arr[arr == 40]

array([40])

In [166]:
arr < 40

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]])

In [167]:
arr[arr < 40]

array([10, 20, 30])

## numpy where function

In [168]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [169]:
np.where(arr < 40)

(array([0, 0, 0], dtype=int64), array([0, 1, 2], dtype=int64))

In [170]:
arr[np.where(arr < 40)]

array([10, 20, 30])

In [171]:
np.where((arr >= 50) & (arr <= 80))

(array([1, 1, 2, 2], dtype=int64), array([1, 2, 0, 1], dtype=int64))

In [172]:
arr[np.where((arr >= 50) & (arr <= 80))]

array([50, 60, 70, 80])

In [173]:
arr[np.where(arr >= 50)]

array([50, 60, 70, 80, 90])

## Array Mathematics

In [174]:
arr1 = np.random.randint(10,51,size = (3,3))
arr2 = np.random.randint(10,51,size = (3,3))

In [175]:
arr1

array([[45, 37, 24],
       [17, 27, 35],
       [10, 19, 28]])

In [176]:
arr2

array([[35, 22, 31],
       [19, 33, 28],
       [31, 28, 24]])

In [177]:
arr1 + arr2

array([[80, 59, 55],
       [36, 60, 63],
       [41, 47, 52]])

In [178]:
np.add(arr1, arr2)

array([[80, 59, 55],
       [36, 60, 63],
       [41, 47, 52]])

In [179]:
arr1 + 20

array([[65, 57, 44],
       [37, 47, 55],
       [30, 39, 48]])

In [180]:
arr1 - arr2

array([[ 10,  15,  -7],
       [ -2,  -6,   7],
       [-21,  -9,   4]])

In [181]:
np.subtract(arr1, arr2)

array([[ 10,  15,  -7],
       [ -2,  -6,   7],
       [-21,  -9,   4]])

In [182]:
arr2 - arr1

array([[-10, -15,   7],
       [  2,   6,  -7],
       [ 21,   9,  -4]])

In [183]:
arr2 - 10

array([[25, 12, 21],
       [ 9, 23, 18],
       [21, 18, 14]])

In [184]:
arr1 * arr2

array([[1575,  814,  744],
       [ 323,  891,  980],
       [ 310,  532,  672]])

In [185]:
np.multiply(arr1, arr2)

array([[1575,  814,  744],
       [ 323,  891,  980],
       [ 310,  532,  672]])

In [186]:
arr1 * 5

array([[225, 185, 120],
       [ 85, 135, 175],
       [ 50,  95, 140]])

In [187]:
arr1 / 5

array([[9. , 7.4, 4.8],
       [3.4, 5.4, 7. ],
       [2. , 3.8, 5.6]])

In [188]:
arr1 / arr2

array([[1.28571429, 1.68181818, 0.77419355],
       [0.89473684, 0.81818182, 1.25      ],
       [0.32258065, 0.67857143, 1.16666667]])

In [189]:
np.divide(arr1, arr2)

array([[1.28571429, 1.68181818, 0.77419355],
       [0.89473684, 0.81818182, 1.25      ],
       [0.32258065, 0.67857143, 1.16666667]])

In [190]:
np.log(20) #base of e

2.995732273553991

In [191]:
np.log2(20) #base of 2

4.321928094887363

In [192]:
np.log10(20)  #base of 10

1.3010299956639813

In [193]:
np.exp(4)

54.598150033144236

In [194]:
np.exp(-3)

0.049787068367863944

## Mean, Median, Min, Max of the Arrays

In [195]:
arr_new = np.random.randint(50,100, size = (10,8))

In [196]:
arr_new

array([[51, 76, 96, 91, 62, 84, 64, 89],
       [54, 80, 80, 77, 64, 98, 87, 51],
       [68, 82, 98, 66, 57, 68, 76, 95],
       [61, 59, 69, 89, 60, 89, 67, 99],
       [59, 58, 80, 64, 98, 85, 84, 89],
       [77, 63, 99, 76, 75, 91, 56, 61],
       [68, 66, 96, 61, 82, 82, 70, 72],
       [64, 89, 61, 77, 80, 98, 90, 77],
       [70, 73, 68, 69, 72, 78, 58, 83],
       [53, 58, 79, 70, 98, 50, 84, 54]])

### mean

In [197]:
np.mean(arr_new)

74.65

In [198]:
np.mean(arr_new, axis = 0)   #column-wise

array([62.5, 70.4, 82.6, 74. , 74.8, 82.3, 73.6, 77. ])

In [199]:
np.mean(arr_new, axis = 1)   #row-wise

array([76.625, 73.875, 76.25 , 74.125, 77.125, 74.75 , 74.625, 79.5  ,
       71.375, 68.25 ])

### meadian


In [200]:
np.median(arr_new)

75.5

In [201]:
np.median(arr_new, axis = 0)

array([62.5, 69.5, 80. , 73. , 73.5, 84.5, 73. , 80. ])

In [202]:
np.median(arr_new, axis = 1)

array([80. , 78.5, 72. , 68. , 82. , 75.5, 71. , 78.5, 71. , 64. ])

### min

In [203]:
np.min(arr_new)

50

In [204]:
np.min(arr_new, axis = 0)

array([51, 58, 61, 61, 57, 50, 56, 51])

In [205]:
np.min(arr_new, axis = 1)

array([51, 51, 57, 59, 58, 56, 61, 61, 58, 50])

### max

In [206]:
np.max(arr_new)

99

In [207]:
np.max(arr_new, axis = 0)

array([77, 89, 99, 91, 98, 98, 90, 99])

In [208]:
np.max(arr_new, axis = 1)

array([96, 98, 98, 99, 98, 99, 96, 98, 83, 98])

### sum

In [209]:
np.sum(arr_new)

5972

In [210]:
np.sum(arr_new, axis = 0)

array([625, 704, 826, 740, 748, 823, 736, 770])

In [211]:
np.sum(arr_new, axis = 1)

array([613, 591, 610, 593, 617, 598, 597, 636, 571, 546])

In [212]:
arr_sum_columns = np.sum(arr_new, axis = 0)

In [213]:
arr_sum_columns[2]

826

In [214]:
arr_sum_columns > 700

array([False,  True,  True,  True,  True,  True,  True,  True])

In [215]:
arr_sum_columns[arr_sum_columns > 700]

array([704, 826, 740, 748, 823, 736, 770])

## Sorting the Arrays

In [216]:
arr_new

array([[51, 76, 96, 91, 62, 84, 64, 89],
       [54, 80, 80, 77, 64, 98, 87, 51],
       [68, 82, 98, 66, 57, 68, 76, 95],
       [61, 59, 69, 89, 60, 89, 67, 99],
       [59, 58, 80, 64, 98, 85, 84, 89],
       [77, 63, 99, 76, 75, 91, 56, 61],
       [68, 66, 96, 61, 82, 82, 70, 72],
       [64, 89, 61, 77, 80, 98, 90, 77],
       [70, 73, 68, 69, 72, 78, 58, 83],
       [53, 58, 79, 70, 98, 50, 84, 54]])

In [217]:
np.sort(arr_new, axis = 0)

array([[51, 58, 61, 61, 57, 50, 56, 51],
       [53, 58, 68, 64, 60, 68, 58, 54],
       [54, 59, 69, 66, 62, 78, 64, 61],
       [59, 63, 79, 69, 64, 82, 67, 72],
       [61, 66, 80, 70, 72, 84, 70, 77],
       [64, 73, 80, 76, 75, 85, 76, 83],
       [68, 76, 96, 77, 80, 89, 84, 89],
       [68, 80, 96, 77, 82, 91, 84, 89],
       [70, 82, 98, 89, 98, 98, 87, 95],
       [77, 89, 99, 91, 98, 98, 90, 99]])

In [218]:
np.sort(arr_new, axis = 1)

array([[51, 62, 64, 76, 84, 89, 91, 96],
       [51, 54, 64, 77, 80, 80, 87, 98],
       [57, 66, 68, 68, 76, 82, 95, 98],
       [59, 60, 61, 67, 69, 89, 89, 99],
       [58, 59, 64, 80, 84, 85, 89, 98],
       [56, 61, 63, 75, 76, 77, 91, 99],
       [61, 66, 68, 70, 72, 82, 82, 96],
       [61, 64, 77, 77, 80, 89, 90, 98],
       [58, 68, 69, 70, 72, 73, 78, 83],
       [50, 53, 54, 58, 70, 79, 84, 98]])

In [219]:
np.sort(arr_new)

array([[51, 62, 64, 76, 84, 89, 91, 96],
       [51, 54, 64, 77, 80, 80, 87, 98],
       [57, 66, 68, 68, 76, 82, 95, 98],
       [59, 60, 61, 67, 69, 89, 89, 99],
       [58, 59, 64, 80, 84, 85, 89, 98],
       [56, 61, 63, 75, 76, 77, 91, 99],
       [61, 66, 68, 70, 72, 82, 82, 96],
       [61, 64, 77, 77, 80, 89, 90, 98],
       [58, 68, 69, 70, 72, 73, 78, 83],
       [50, 53, 54, 58, 70, 79, 84, 98]])

In [220]:
arr_1d = np.random.randint(45, 98, size = 8)

In [221]:
arr_1d

array([54, 62, 77, 46, 80, 72, 78, 57])

In [222]:
np.sort(arr_1d)

array([46, 54, 57, 62, 72, 77, 78, 80])

In [223]:
np.argsort(arr_1d)

array([3, 0, 7, 1, 5, 2, 6, 4], dtype=int64)

## Array Manipulation

- np.concatenate
- np.hstack
- np.vstack
- np.column_stack
- np.hsplit
- np.vsplit

In [224]:
arr3 = np.random.randint(10, 50, size = (5,5))
arr4 = np.random.randint(10, 50, size = (5,5))

### hstack

In [249]:
hstacked_arr = np.hstack((arr3, arr4))
hstacked_arr

array([[22, 29, 39, 48, 32, 36, 22, 24, 44, 37],
       [36, 24, 19, 11, 23, 11, 44, 43, 47, 11],
       [21, 16, 20, 10, 38, 28, 17, 21, 28, 43],
       [41, 33, 46, 14, 12, 48, 26, 11, 20, 49],
       [43, 26, 17, 46, 38, 11, 18, 20, 49, 41]])

### vstack

In [228]:
np.vstack((arr3, arr4))

array([[22, 29, 39, 48, 32],
       [36, 24, 19, 11, 23],
       [21, 16, 20, 10, 38],
       [41, 33, 46, 14, 12],
       [43, 26, 17, 46, 38],
       [36, 22, 24, 44, 37],
       [11, 44, 43, 47, 11],
       [28, 17, 21, 28, 43],
       [48, 26, 11, 20, 49],
       [11, 18, 20, 49, 41]])

### concatenate

In [229]:
np.concatenate((arr3, arr4), axis = 0)  #similar to vstack

array([[22, 29, 39, 48, 32],
       [36, 24, 19, 11, 23],
       [21, 16, 20, 10, 38],
       [41, 33, 46, 14, 12],
       [43, 26, 17, 46, 38],
       [36, 22, 24, 44, 37],
       [11, 44, 43, 47, 11],
       [28, 17, 21, 28, 43],
       [48, 26, 11, 20, 49],
       [11, 18, 20, 49, 41]])

In [230]:
np.concatenate((arr3, arr4), axis = 1)  #similar to hstack

array([[22, 29, 39, 48, 32, 36, 22, 24, 44, 37],
       [36, 24, 19, 11, 23, 11, 44, 43, 47, 11],
       [21, 16, 20, 10, 38, 28, 17, 21, 28, 43],
       [41, 33, 46, 14, 12, 48, 26, 11, 20, 49],
       [43, 26, 17, 46, 38, 11, 18, 20, 49, 41]])

### column_stack

In [251]:
arr_flat = np.arange(5)
np.column_stack((arr3, arr_flat))

array([[22, 29, 39, 48, 32,  0],
       [36, 24, 19, 11, 23,  1],
       [21, 16, 20, 10, 38,  2],
       [41, 33, 46, 14, 12,  3],
       [43, 26, 17, 46, 38,  4]])

### hsplit

In [256]:
arr_big = np.random.randint(10, 80, size = (10,8))
arr11, arr12 = np.hsplit(arr_big, 2)  #column-wise
print(arr11)
print("")
print(arr12)

[[67 72 63 68]
 [17 38 39 67]
 [64 22 23 69]
 [67 35 77 57]
 [77 15 49 14]
 [31 17 59 72]
 [60 37 13 35]
 [18 79 63 53]
 [78 55 79 20]
 [51 15 31 55]]

[[50 10 56 62]
 [19 11 43 73]
 [60 47 61 42]
 [58 74 59 17]
 [11 43 14 68]
 [12 45 77 39]
 [63 34 65 20]
 [77 77 73 75]
 [68 24 41 29]
 [44 34 72 31]]


### vsplit

In [238]:
np.vsplit(arr_big, 2)  #row-wise

[array([[70, 50, 55, 22, 42, 30, 59, 61],
        [48, 48, 48, 40, 61, 42, 72, 61],
        [45, 54, 57, 63, 61, 68, 72, 75],
        [16, 71, 25, 49, 76, 66, 70, 67],
        [68, 67, 36, 14, 19, 18, 55, 20]]),
 array([[68, 19, 63, 20, 68, 10, 69, 12],
        [73, 77, 76, 48, 30, 35, 28, 51],
        [49, 43, 13, 23, 26, 29, 50, 30],
        [44, 79, 36, 75, 49, 54, 10, 50],
        [77, 24, 62, 62, 45, 32, 66, 10]])]

## Array Inspection

In [239]:
arr_big

array([[70, 50, 55, 22, 42, 30, 59, 61],
       [48, 48, 48, 40, 61, 42, 72, 61],
       [45, 54, 57, 63, 61, 68, 72, 75],
       [16, 71, 25, 49, 76, 66, 70, 67],
       [68, 67, 36, 14, 19, 18, 55, 20],
       [68, 19, 63, 20, 68, 10, 69, 12],
       [73, 77, 76, 48, 30, 35, 28, 51],
       [49, 43, 13, 23, 26, 29, 50, 30],
       [44, 79, 36, 75, 49, 54, 10, 50],
       [77, 24, 62, 62, 45, 32, 66, 10]])

In [240]:
arr_big.shape   #(no of rows, no of cols)

(10, 8)

In [241]:
arr_big.size   #total items present in the array

80

In [242]:
arr_big.ndim   #check the dimension of the array

2

In [243]:
arr_big.dtype

dtype('int32')

In [244]:
arr_big.T   #transpose of the array

array([[70, 48, 45, 16, 68, 68, 73, 49, 44, 77],
       [50, 48, 54, 71, 67, 19, 77, 43, 79, 24],
       [55, 48, 57, 25, 36, 63, 76, 13, 36, 62],
       [22, 40, 63, 49, 14, 20, 48, 23, 75, 62],
       [42, 61, 61, 76, 19, 68, 30, 26, 49, 45],
       [30, 42, 68, 66, 18, 10, 35, 29, 54, 32],
       [59, 72, 72, 70, 55, 69, 28, 50, 10, 66],
       [61, 61, 75, 67, 20, 12, 51, 30, 50, 10]])

In [245]:
arr_big.flatten()  #convert a higher dimension array to 1d

array([70, 50, 55, 22, 42, 30, 59, 61, 48, 48, 48, 40, 61, 42, 72, 61, 45,
       54, 57, 63, 61, 68, 72, 75, 16, 71, 25, 49, 76, 66, 70, 67, 68, 67,
       36, 14, 19, 18, 55, 20, 68, 19, 63, 20, 68, 10, 69, 12, 73, 77, 76,
       48, 30, 35, 28, 51, 49, 43, 13, 23, 26, 29, 50, 30, 44, 79, 36, 75,
       49, 54, 10, 50, 77, 24, 62, 62, 45, 32, 66, 10])

In [246]:
arr_big.reshape(16, -1)

array([[70, 50, 55, 22, 42],
       [30, 59, 61, 48, 48],
       [48, 40, 61, 42, 72],
       [61, 45, 54, 57, 63],
       [61, 68, 72, 75, 16],
       [71, 25, 49, 76, 66],
       [70, 67, 68, 67, 36],
       [14, 19, 18, 55, 20],
       [68, 19, 63, 20, 68],
       [10, 69, 12, 73, 77],
       [76, 48, 30, 35, 28],
       [51, 49, 43, 13, 23],
       [26, 29, 50, 30, 44],
       [79, 36, 75, 49, 54],
       [10, 50, 77, 24, 62],
       [62, 45, 32, 66, 10]])

In [247]:
arr_big.reshape(-1, 5)

array([[70, 50, 55, 22, 42],
       [30, 59, 61, 48, 48],
       [48, 40, 61, 42, 72],
       [61, 45, 54, 57, 63],
       [61, 68, 72, 75, 16],
       [71, 25, 49, 76, 66],
       [70, 67, 68, 67, 36],
       [14, 19, 18, 55, 20],
       [68, 19, 63, 20, 68],
       [10, 69, 12, 73, 77],
       [76, 48, 30, 35, 28],
       [51, 49, 43, 13, 23],
       [26, 29, 50, 30, 44],
       [79, 36, 75, 49, 54],
       [10, 50, 77, 24, 62],
       [62, 45, 32, 66, 10]])